/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        Primary: "#2466A8",
        PrimaryContainer: "#205F94",
        SecondaryContainer: "#C71C55",
        Tertiary: "#8C5000",
        TertiaryContainer: "#FB9515",
        OnTertiaryContainer: "#381C00",
        Error: "#4A0002",
        ErrorContainer: "#821311",
        OnErrorContainer: "#FFCAC4",
        Surface: "#F8FAFC",
        OnSurface: "#243342",
        SurfaceVariant: "#E0E3E5",
        OnSurfaceVariant: "#73808C",
        InverseOnSurface: "#F0F2F4",
        Outline: "#74777A",
        OutlineVariant: "#C4C7C9",
        InverseSurface: "#303131",
        InverseOnSurface: "#EFF1F3",
        InversePrimary: "#9CCAFF",
        SurfaceContainerLow: "#F2F4F6",
        SurfaceContainer: "#EDEFF1",
        SurfaceContainerHigh: "#E7E9EB",
        SurfaceContainerHighest: "#E1E3E5",
        SurfaceTint: "#246297",
        Background: "#F8FBFE",
        OnBackground: "#191C1F",
        PrimaryFixed: "#D0E4FF",
        OnPrimaryFixed: "#001D35",
        PrimaryFixedDim: "#9CCAFF",
        OnPrimaryFixedVariant: "#00497A",
        SecondaryFixed: "#FFD9DE",
        OnSecondaryFixed: "#400014",
        SecondaryFixedDim: "#FFB2BE",
        OnSecondaryFixedVariant: "#660025",
        TertiaryFixed: "#FFDCBF",
        OnTertiaryFixed: "#2D1600",
        TertiaryFixedDim: "#FFB873",
        OnTertiaryFixedVariant: "#6A3B00",
        SurfaceDim: "#D9DBDC",
        SurfaceBright: "#F9FBFC",
        secondary: '#80BB9C',
        navyDeep: "#182F4B",
        cyanLight: "#1CC2C4",
        grayLight: "#9DA7B3",
        blueDeep: "#0A2342",
        bluemaxLight: "#12335A",
        lightRed: "#D81E5B",
        maxLightRed: "#FDF1F5",
        primaryFixed : "#D0ECFF",
        primaryFixedVariant : "#00497B",
        whiteGray: "#E1EAF2",
        whiteGrayLight: "#CED3D9",
      },
      fontFamily: {
        ubunto: ["var(--font-ubuntu)"],
        sansation: [`var(--font-sansation)`],
      },
      keyframes: {
        ['t-right']: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0%)' },
        },
        ['t-left']: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0%)' },
        },
        ['fade-in']: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        ['blink-caret']: {
          '0%, 100%': { borderColor: 'transparent' },
          '50%': { borderColor: '#b1b1b1' },
        },
      },
      animation: {
        't-right': 't-right 1.5s ease forwards',
        't-left': 't-left 1.5s ease forwards',
        'fade-in': 'fade-in 2.2s ease forwards',
        'blink-caret': 'blink-caret 0.75s step-end infinite',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      }
    },
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      '3xl': '1998px',
    },
  },
  darkMode:['selector', '[data-mode="dark"]'],
  plugins: [],
}
